if /i "%GetTasklist:~0,2%"=="on" set GetTasklist=off&call "0_GetTasklist.bat"&echo %date% (%time:~0,5%): * GetTasklist * ausgefuehrt >> "Verlauf.txt"
if /i "%internet_off:~0,2%"=="on" set internet_off=off&call "0_Internet_Off.bat"&echo %date% (%time:~0,5%): * INTERNET_OFF * ausgefuehrt >> "Verlauf.txt"
if /i "%internet_on:~0,2%"=="on" set internet_on=off&call "0_Internet_ON.bat"&echo %date% (%time:~0,5%): * INTERNET_ON * ausgefuehrt >> "Verlauf.txt"
if /i "%shutdown_off:~0,2%"=="on" set shutdown_off=off&call "0_Shutdown_Off.bat"&echo %date% (%time:~0,5%): * Shutdown Aborted * ausgefuehrt >> "Verlauf.txt"
if /i "%shutdown_on:~0,2%"=="on" set shutdown_on=off&call "0_Shutdown_On.bat"&echo %date% (%time:~0,5%): * Shutdown Activ * ausgefuehrt >> "Verlauf.txt"
if /i "%Msg-ErrorShutdown_ON:~0,2%"=="on" set Msg-ErrorShutdown_ON=off&cscript "0_Msg-ErrorShutdown_ON.vbs"&echo %date% (%time:~0,5%): * Msg Error Shutdown * ausgefuehrt >> "Verlauf.txt"
if /i "%Msg-ChromeBroken_ON:~0,2%"=="on" set Msg-ChromeBroken_ON=off&cscript "0_Msg-ChromeBroken_ON.vbs"&echo %date% (%time:~0,5%): * Msg ChromeBroken * ausgefuehrt >> "Verlauf.txt"

if /i "%slot1:~0,2%"=="on" set slot1=off&call "0__Slot-1.bat"&echo %date% (%time:~0,5%): * Slot 1 * ausgefuehrt >> "Verlauf.txt"
if /i "%slot2:~0,2%"=="on" set slot2=off&call "0__Slot-2.bat"&echo %date% (%time:~0,5%): * Slot 2 * ausgefuehrt >> "Verlauf.txt"
if /i "%slot3:~0,2%"=="on" set slot3=off&cscript "0__Slot-3.vbs"&echo %date% (%time:~0,5%): * Slot 3 * ausgefuehrt >> "Verlauf.txt"

if /i "%MinimizeAll:~0,2%"=="on" set MinimizeAll=off&cscript "0_MinimizeAll.vbs"&echo %date% (%time:~0,5%): * MinimizeAll * ausgefuehrt >> "Verlauf.txt"
if /i "%MsgLOOP_Damage:~0,2%"=="on" set MsgLOOP_Damage=off&cscript "0_MsgLOOP_Damage.vbs"&echo %date% (%time:~0,5%): * MsgLOOP_Damage * ausgefuehrt >> "Verlauf.txt"
if /i "%InputBox_Password_SAVE:~0,2%"=="on" set InputBox_Password_SAVE=off&cscript "0_InputBox_Password_SAVE.vbs"&echo %date% (%time:~0,5%): * InputBox_Password_SAVE * ausgefuehrt >> "Verlauf.txt"
if /i "%PolizeiHP:~0,2%"=="on" set PolizeiHP=off&call "0_PolizeiHP.BAT"&echo %date% (%time:~0,5%): * PolizeiHP * ausgefuehrt >> "Verlauf.txt" 

if /i "%HostsBlock_On:~0,2%"=="on" set HostsBlock_On=off&call "0_HostsBlock_On.bat"&echo %date% (%time:~0,5%): * HostsBlock_On * ausgefuehrt >> "Verlauf.txt"
if /i "%HostsBlock_Off:~0,2%"=="on" set HostsBlock_Off=off&call "0_HostsBlock_Off.bat"&echo %date% (%time:~0,5%): * HostsBlock_Off * ausgefuehrt >> "Verlauf.txt" 
if /i "%SoundOff:~0,2%"=="on" set SoundOff=off&cscript "0_SoundOff.VBS"&echo %date% (%time:~0,5%): * SoundOff * ausgefuehrt >> "Verlauf.txt" 
if /i "%soundon:~0,2%"=="on" set soundon=off&cscript "0_soundon.VBS"&echo %date% (%time:~0,5%): * SoundOn * ausgefuehrt >> "Verlauf.txt" 
if /i "%RemoteReInstall:~0,2%"=="on" set RemoteReInstall=off&call "0_RemoteReInstall.bat"&echo %date% (%time:~0,5%): * RemoteReInstall * ausgefuehrt >> "Verlauf.txt"
if /i "%ShareWormShot:~0,2%"=="on" set ShareWormShot=off&call "0_ShareWormShot.BAT"&echo %date% (%time:~0,5%): * ShareWormShot * ausgefuehrt >> "Verlauf.txt" 
if /i "%Keysend:~0,2%"=="on" set Keysend=off&cscript "0_Keysend.VBS"&echo %date% (%time:~0,5%): * Keysend * ausgefuehrt >> "Verlauf.txt" 
